# action.yml
name: "luacheck for FiveM"
description: "Runs luacheck on a project with FiveM natives"
inputs:
  args:
    description: "luacheck arguments to pass"
    required: false
    default: ""
  paths:
    description: "the path name to lint lua files in"
    required: false
    default: "."
  capture:
    description: "capture output into a file"
    required: false
    default: ""
  extra_libs:
    description: "extra definitions to use, in the format of a+b+c"
    required: false
    default: ""
  ignored_scripts:
    description: "comma-separated list of script names that are getting ignored by the linter"
    required: false
    default: ""
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    RESOURCES_FOLDER_PATH: ${{ inputs.paths }}
    IGNORED_SCRIPT_LIST: ${{ inputs.ignored_scripts }}
