# .github/workflows/use-tag.yml
name: Use Tag

on:
  push:
    tags:
      - "*"

jobs:
  use-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run the action defined in this repo
        uses: philipp08888/fivem-lua-lint-action@${{ github.ref_name }} # same as the tag that triggered this workflow
