# .github/workflows/create-tag.yml
name: Create Tag

on:
  push:
    branches: [master]

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Workflow
        uses: philipp08888/fivem-lua-lint-action@master
