name: Create Commit Tag

on:
  push:
    branches:
      - master

jobs:
  tag-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Move 'latest' tag to current commit
        run: |
          git tag -f latest
          git push -f origin latest

      - name: lint
        uses: philipp08888/fivem-lua-lint-action@latest
        with:
          paths: ./tests/
